const Interests = [
  "Gaming",
  "Language",
  "Painting",
  "Football",
  "Cricket",
  "web design",
  "web development",
  "Hiking",
  "Camping",
  "Bird Watching",
  "Fishing",
  "Kayaking and Canoeing",
  "Rock Climbing",
  "Stargazing",
  "Wildlife Photography",
  "Backpacking",
  "Mountain Biking",
  "Nature Conservation",
  "Beachcombing",
  "Botany and Plant Study",
  "Gardening (Vegetable, Flower)",
  "Foraging Wild Edibles",
  "Sailing",
  "Horseback Riding",
  "Fossil Hunting",
  "Surfing",
  "Beekeeping",
  "Geocaching",
  "Landscape Photography",
  "Trail Running",
  "Tree Climbing",
  "Environmental Advocacy",
  "Mushroom Hunting",
  "Scuba Diving",
  "Snorkeling",
  "River Rafting",
  "Orienteering",
  "Painting (Oil, Acrylic, Watercolor)",
  "Drawing and Sketching",
  "Pottery and Ceramics",
  "Sculpting",
  "Knitting and Crocheting",
  "Sewing and Quilting",
  "Scrapbooking",
  "Calligraphy and Hand Lettering",
  "Woodworking",
  "Jewelry Making",
  "Embroidery",
  "Metalworking",
  "Candle Making",
  "Soap Making",
  "Origami",
  "Glassblowing",
  "Leathercraft",
  "Stained Glass Art",
  "Beadwork",
  "Macrame",
  "Paper Crafting",
  "Textile Dyeing",
  "Printmaking",
  "Basket Weaving",
  "Mosaic Art",
  "Resin Art",
  "Weaving and Looming",
  "Bookbinding",
  "Miniature Model Making",
  "Fiber Arts",
  "Playing a Musical Instrument (Guitar, Piano, Violin, etc.)",
  "Singing and Vocal Training",
  "Songwriting",
  "Music Production",
  "DJing",
  "Dance (Ballet, Hip-Hop, Ballroom, etc.)",
  "Theater Acting",
  "Improvisational Comedy",
  "Stand-Up Comedy",
  "Opera Singing",
  "Music Composition",
  "Choreography",
  "Audio Engineering",
  "Musical Theater",
  "Spoken Word Poetry",
  "Voice Acting",
  "Mime",
  "Classical Music Appreciation",
  "Orchestral Conducting",
  "Public Speaking and Oratory Skills",
  "Lip Syncing",
  "Beatboxing",
  "Music Theory",
  "Record Collecting",
  "Concert Photography",
  "Dance Fitness (Zumba, Jazzercise)",
  "Puppet Making and Puppeteering",
  "Busking (Street Performing)",
  "Digital Music Sampling",
  "Folk Dancing",
  "Running and Jogging",
  "Swimming",
  "Weightlifting",
  "Gymnastics",
  "Martial Arts (Karate, Judo, Taekwondo)",
  "Tennis",
  "Basketball",
  "Soccer",
  "Golf",
  "Baseball and Softball",
  "Cycling (Road, Mountain)",
  "Skateboarding",
  "Skiing (Alpine, Cross-Country)",
  "Snowboarding",
  "Yoga",
  "Pilates",
  "Fencing",
  "Archery",
  "Boxing",
  "Rowing",
  "Volleyball",
  "Badminton",
  "Rock Climbing (Indoor)",
  "Table Tennis",
  "Wrestling",
  "Bowling",
  "Sculling",
  "Squash",
  "Rugby",
  "Ultimate Frisbee",
  "Video Gaming (PC, Console)",
  "Tabletop Gaming (D&D, Warhammer)",
  "Board Games (Chess, Monopoly, Settlers of Catan)",
  "Card Games (Poker, Bridge, Solitaire)",
  "Puzzle Solving (Crossword, Sudoku)",
  "Escape Rooms",
  "Collectible Card Games (Magic: The Gathering)",
  "Jigsaw Puzzles",
  "Brain Teasers and Logic Puzzles",
  "Miniature Wargaming",
  "Virtual Reality Gaming",
  "Speedcubing (Rubik’s Cube)",
  "Word Search Puzzles",
  "Bingo",
  "eSports Watching and Participation",
  "Building Puzzle Boxes",
  "Role-Playing Games (RPGs)",
  "Memory Games",
  "Trivia and Quiz Games",
  "Scavenger Hunts",
  "Augmented Reality Gaming",
  "Fantasy Sports Leagues",
  "Chess Problem Solving",
  "Mahjong",
  "Fiction Reading (Novels, Short Stories)",
  "Non-Fiction Reading (Biographies, Memoirs)",
  "Poetry Writing and Appreciation",
  "Creative Writing (Short Stories, Flash Fiction)",
  "Blogging and Vlogging",
  "Screenwriting",
  "Playwriting",
  "Essay Writing",
  "Journalism",
  "Reading Classic Literature",
  "Book Collecting",
  "Comic Book and Graphic Novel Reading",
  "Fan Fiction Writing",
  "Science Fiction and Fantasy Reading",
  "Mystery Novel Reading",
  "Memoir and Autobiography Writing",
  "Literary Analysis",
  "Writing for Social Media",
  "Editing and Proofreading",
  "Self-Publishing",
  "Travel Writing",
  "Horror and Thriller Reading",
  "Historical Fiction Reading",
  "Writing Poetry",
  "Magazine Reading (Science, Fashion, etc.)",
  "Philosophical Literature",
  "Short Story Anthologies",
  "Fictional Worldbuilding",
  "Nature Writing",
  "Book Club Participation",
  "Robotics and Electronics",
  "Astronomy and Stargazing",
  "Coding and Programming",
  "3D Printing",
  "Amateur Radio (Ham Radio)",
  "Model Rocketry",
  "Virtual Reality Development",
  "Drones and Drone Photography",
  "Space Exploration Interest",
  "Weather Observation",
  "Artificial Intelligence and Machine Learning",
  "Quantum Computing Basics",
  "Bioinformatics",
  "Data Science and Analysis",
  "Home Automation (Smart Home Tech)",
  "Cybersecurity and Ethical Hacking",
  "Paleontology and Fossil Collecting",
  "Collecting Minerals and Crystals",
  "Model Railroading",
  "Space and Planetary Science",
  "Cryptography",
  "Renewable Energy and Solar Power",
  "Astrophotography",
  "Internet of Things (IoT) Projects",
  "Nanotechnology",
  "Chemistry Experiments",
  "Science Fairs and Competitions",
  "Physics and Theoretical Physics",
  "Marine Biology",
  "Electronics Tinkering",
  "Solo Travel",
  "Road Tripping",
  "Cultural Travel",
  "Food Tourism",
  "Hiking and Trekking in Foreign Countries",
  "Backpacking Across Continents",
  "RV and Camper Travel",
  "Heritage Site Exploration",
  "Photography-Based Travel",
  "Off-the-Beaten-Path Travel",
  "Cruise Travel",
  "Adventure Tourism (Skydiving, Zip-lining)",
  "Luxury Travel",
  "Exploring Small Towns",
  "History and Archaeology Travel",
  "Wildlife Safaris",
  "Camping in National Parks",
  "Snow Adventures (Skiing, Snowboarding)",
  "Architectural Tours",
  "City Exploration and Urban Hikes",
  "Scenic Train Journeys",
  "Backpacking Through National Parks",
  "UNESCO World Heritage Site Visits",
  "Overland Adventure Travel",
  "Jungle and Rainforest Exploration",
  "Desert Expeditions",
  "Bike Touring",
  "Religious Pilgrimages",
  "Eco-Tourism",
  "Cultural Festivals and Events Travel",
  "Baking (Bread, Pastries, Cakes)",
  "Cooking International Cuisines",
  "Wine Tasting and Sommelier Skills",
  "Craft Beer Brewing",
  "Coffee Brewing and Tasting",
  "Cake Decorating",
  "Cocktail Mixing and Bartending",
  "Fermenting Foods (Sauerkraut, Kimchi)",
  "Charcuterie Board Making",
  "Cheese Making",
  "Vegan and Vegetarian Cooking",
  "Food Blogging",
  "Street Food Exploration",
  "Culinary Travel",
  "Baking with Alternative Ingredients",
  "Raw Food Preparation",
  "Slow Cooking Techniques",
  "Spice Blending",
  "Canning and Food Preservation",
  "BBQ and Grilling",
  "Organic Gardening for Cooking",
  "Low-Carb and Keto Cooking",
  "Tea Blending and Tasting",
  "Sugar Art and Candy Making",
  "Plant-Based Cooking",
  "Foraging and Wild Edibles",
  "Italian Cooking",
  "French Pâtisserie Techniques",
  "Sourdough Bread Making",
  "Chocolate Making",
  "Coin Collecting (Numismatics)",
  "Stamp Collecting (Philately)",
  "Antique Collecting",
  "Toy Collecting",
  "Comic Book Collecting",
  "Vintage Car Collecting",
  "Watch Collecting",
  "Vintage Clothing Collecting",
  "Vinyl Record Collecting",
  "Art Collecting",
  "Shell Collecting",
  "Baseball Card Collecting",
  "Movie Memorabilia Collecting",
  "Model Train Collecting",
  "Fossil Collecting",
  "Military Memorabilia",
  "Crystal and Mineral Collecting",
  "Autograph Collecting",
  "Collecting Action Figures",
  "Sports Memorabilia Collecting",
  "Vintage Technology Collecting",
  "Board Game Collecting",
  "Vintage Jewelry Collecting",
  "Postcard Collecting",
  "Seashell Collecting",
  "Model Airplane Collecting",
  "Camera Collecting",
  "Vinyl Figure Collecting (Funko, etc.)",
  "Music Box Collecting",
  "Book Collecting (First Editions, Rare)",
  "Meditation and Mindfulness",
  "Running and Marathon Training",
  "Weightlifting and Strength Training",
  "CrossFit",
  "Cycling",
  "Hiking for Fitness",
  "Bodybuilding",
  "Aerobics",
  "Stretching and Flexibility",
  "Calisthenics",
  "Martial Arts (Boxing, Kickboxing)",
  "Tai Chi",
  "Personal Fitness Tracking",
  "Mindful Eating",
  "Breathing Exercises",
  "Balance Training",
  "Functional Fitness",
  "Fitness Classes (Spin, Barre)",
  "Hiking for Mental Health",
  "Mindful Walking",
  "Wilderness Survival Skills",
  "Nutrition and Diet Planning",
  "Herbalism and Holistic Health",
  "Guided Meditation Practices",
  "Interval Training",
  "Self-Care Practices",
  "Home Decor and Interior Design",
  "Woodworking and Carpentry",
  "Furniture Restoration and Repurposing",
  "Gardening and Landscaping",
  "Home Automation",
  "DIY Craft Projects",
  "Houseplant Care",
  "Remodeling and Renovation",
  "DIY Painting and Wallpapering",
  "Building Outdoor Structures",
  "Sewing and Upholstery",
  "Electrical Repairs",
  "Plumbing Basics",
  "Minimalist Home Design",
  "Solar Power Installation",
  "Organizing and Decluttering",
  "Tile Setting and Grouting",
  "Small Engine Repair",
  "Home Security System Installation",
  "Insulation and Weatherproofing",
  "Eco-Friendly Home Projects",
  "DIY Lighting Fixtures",
  "Creating Outdoor Living Spaces",
  "Smart Home Setup",
  "Concrete and Masonry Work",
  "Garden Planning and Design",
  "DIY Flooring",
  "DIY Shelving and Storage Solutions",
  "Home Theater Installation",
  "Recycling and Upcycling",
  "Learning New Languages",
  "Public Speaking and Oratory",
  "Self-Help and Personal Development",
  "Speed Reading",
  "Memory Improvement Techniques",
  "Mind Mapping",
  "Critical Thinking Skills",
  "Life Coaching",
  "Financial Literacy",
  "Online Course Participation",
  "Skill-Building Workshops",
  "Study Techniques and Hacks",
  "Cognitive Psychology",
  "Problem-Solving Skills",
  "Meditation and Stress Reduction",
  "Personal Branding",
  "Emotional Intelligence",
  "Goal Setting and Achievement",
  "Personal Finance Management",
  "Developing Leadership Skills",
  "Learning Soft Skills",
  "Writing and Reflective Journaling",
  "Time Management",
  "Practicing Gratitude",
  "Setting Up Vision Boards",
  "Digital Organization and Productivity",
  "Career Development Planning",
  "Finding Life Purpose",
  "Learning Social Skills",
  "Developing Assertiveness",
  "Fashion Design",
  "Personal Styling",
  "Sewing and Tailoring",
  "Accessory Design (Bags, Belts)",
  "DIY Clothing Alterations",
  "Fashion Blogging",
  "Sustainable Fashion Practices",
  "Makeup Artistry",
  "Nail Art",
  "Jewelry Design",
  "Cosplay and Costume Design",
  "Fashion Photography",
  "Modeling and Runway",
  "Capsule Wardrobe Creation",
  "Closet Organization",
  "Vintage Fashion Collection",
  "Wardrobe Styling for Photoshoots",
  "Fashion Illustration",
  "Trend Forecasting",
  "Personal Grooming",
  "Men’s Fashion and Styling",
  "Fashion History",
  "Upcycling Old Clothing",
  "Seasonal Wardrobe Planning",
  "Styling for Plus Size",
  "Cultural Fashion (Traditional Wear)",
  "Hair Styling Techniques",
  "Thrift Shopping",
  "Wedding Styling",
  "Luxury Fashion Brands Exploration",
  "Volunteering and Community Service",
  "Genealogy and Ancestry Research",
  "Cultural Studies and Anthropology",
  "Language Exchange",
  "Visiting Museums and Art Galleries",
  "Attending Cultural Festivals",
  "Political Activism",
  "History Research and Study",
  "Philosophy and Ethics",
  "Exploring Different Religions",
  "Social Justice and Advocacy",
  "Public Policy Awareness",
  "Folklore and Mythology Study",
  "Attending Literary Festivals",
  "Attending Theater Performances",
  "Historical Reenactments",
  "Interfaith Dialogue and Study",
  "International Relations Awareness",
  "Social Work",
  "Human Rights Activism",
  "International Cuisine Exploration",
  "Local History Research",
  "Sociology and Social Behavior",
  "Study of Ancient Civilizations",
  "Street Art Appreciation",
  "Independent Film Watching",
  "Peace Studies and Conflict Resolution",
  "Studying Ancient Scripts and Languages",
  "Cultural Anthropology",
  "Attending Opera Performances",
  "Dog Training and Obedience",
  "Cat Care and Grooming",
  "Exotic Pet Care",
  "Aquascaping for Fish Tanks",
  "Bird Watching and Bird Care",
  "Dog Walking",
  "Pet Grooming Skills",
  "Animal Rescue Volunteering",
  "Horseback Riding and Horse Care",
  "Pet Photography",
  "Reptile and Amphibian Care",
  "Pet Sitting",
  "Animal Behavior Observation",
  "Building Animal Habitats",
  "Pet Nutrition and Diet Planning",
  "Breeding and Raising Small Animals",
  "Participating in Pet Shows",
  "Aquatic Pet Keeping",
  "Dog Agility Training",
  "Pet Fashion and Accessories",
  "Animal Shelter Support",
  "Rabbit and Small Mammal Care",
  "Animal-Assisted Therapy",
  "Pet Safety and First Aid",
  "Animal Rights Awareness",
  "Learning Animal Communication",
  "Community Dog Parks and Socializing",
  "Building Pet Enrichment Toys",
  "Rescue and Adoption Awareness",
  "Training Therapy Animals",
  "Stock Market Investing",
  "Real Estate Investment",
  "Cryptocurrency Trading",
  "Personal Budgeting",
  "Saving and Wealth Building",
  "Collecting Gold and Precious Metals",
  "Mutual Funds and ETFs",
  "Retirement Planning",
  "Forex Trading",
  "Dividend Investing",
  "Passive Income Streams",
  "Portfolio Management",
  "Angel Investing",
  "Peer-to-Peer Lending",
  "Tax Planning and Strategies",
  "Sustainable Investing (ESG)",
  "Financial Literacy Education",
  "Value Investing",
  "Financial Planning for Families",
  "Options and Futures Trading",
  "Venture Capital Basics",
  "Learning Financial Analysis",
  "Rental Property Management",
  "Stock Analysis and Valuation",
  "Compound Interest Savings",
  "Budgeting for Travel and Leisure",
  "Creating Emergency Funds",
  "Debt Reduction Techniques",
  "Understanding Inflation",
  "Crowdfunding Investments",
  "Car Restoration and Modification",
  "Motorcycle Maintenance and Riding",
  "Classic Car Collecting",
  "Off-Road Driving",
  "Electric Vehicle Technology",
  "Automotive Detailing",
  "Go-Kart Racing",
  "Vehicle Tuning and Performance",
  "Auto Body Repair",
  "DIY Car Repairs",
  "Building and Maintaining Bicycles",
  "Engine Repair and Tuning",
  "Learning Automotive Electronics",
  "Understanding Car Suspension Systems",
  "Collecting Die-Cast Models",
  "Antique Vehicle Restoration",
  "Car Audio Installation",
  "Racing Simulator Setups",
  "Road Trip Planning",
  "Driving on Racing Tracks",
  "Boat Maintenance and Repair",
  "Drone Mechanics and Flying",
  "Participating in Car Shows",
  "DIY Engine Rebuilds",
  "Designing Custom Car Interiors",
  "Tire and Brake Maintenance",
  "Car Photography",
  "Collecting License Plates",
  "Tinkering with Small Engines",
  "Drone Racing",
  "Starting a Small Business",
  "Freelancing",
  "E-commerce Store Management",
  "Blogging as a Business",
  "Networking and Business Connections",
  "Consulting",
  "Building Passive Income",
  "Dropshipping",
  "Crafting a Business Plan",
  "Product Development",
  "Digital Marketing",
  "Affiliate Marketing",
  "Business Analytics",
  "Social Media Management",
  "Business Strategy Planning",
  "Crowdfunding Campaigns",
  "Venture Capital Exploration",
  "Customer Experience Design",
  "Public Relations for Small Businesses",
  "Learning Accounting Basics",
  "Human Resources Management",
  "Starting a Franchise",
  "Financial Forecasting",
  "Market Research",
  "Customer Relationship Management",
  "Sales Funnel Creation",
  "Business Writing and Blogging",
  "Event Planning for Businesses",
  "Negotiation Skills Development",
  "Family Travel Planning",
  "Homeschooling Techniques",
  "Parenting for Different Age Groups",
  "Child Development and Learning",
  "Baby Care and Infant Development",
  "Crafting with Kids",
  "Organizing Family Events",
  "Family Photography",
  "Parenting Support Groups",
  "Teaching Kids Financial Literacy",
  "Family Fitness and Outdoor Activities",
  "Positive Parenting Techniques",
  "Nutrition and Meal Planning for Families",
  "Navigating Parenthood and Career Balance",
  "Building Family Traditions",
  "Supporting Children’s Mental Health",
  "Special Needs Parenting",
  "Family Game Nights",
  "Teaching Kids Practical Skills",
  "Pet Parenting for Families",
  "Coordinating Family Volunteering",
  "Preparing for New Baby",
  "Family Recipe Collecting",
  "Family Scrapbooking",
  "Parenting Through Adolescence",
  "Toddler Activities and Crafts",
  "Storytelling with Kids",
  "Preparing Kids for School",
  "DIY Family Holiday Decor",
  "Family Camping and Hiking",
  "Vintage Toy Collecting",
  "Antique Furniture Collecting",
  "Collecting Movie Posters",
  "Sports Cards Collecting",
  "Rare Book Collecting",
  "Collecting Artifacts and Relics",
  "Collecting Vintage Advertising",
  "Coin and Currency Collection",
  "Firearms Collecting (Historical)",
  "Souvenir Collecting from Travels",
  "Collecting War Memorabilia",
  "Fountain Pen Collecting",
  "Glass Bottle Collecting",
  "Thimble Collecting",
  "Historical Documents and Manuscripts",
  "Vintage Electronics Collecting",
  "Political Memorabilia",
  "Collecting Vintage Tools",
  "Collecting Limited Edition Figures",
  "Collecting Maps and Atlases",
  "Doll Collecting",
  "Collecting Perfume Bottles",
  "Record and Vinyl Collecting",
  "Collecting Casino Chips",
  "Marbles Collecting",
  "Antique Clocks Collecting",
  "Medal and Badge Collecting",
  "Vintage Posters and Prints",
  "Writing Novels and Stories",
  "Writing Poetry and Prose",
  "Fiction Writing (Fantasy, Sci-Fi, etc.)",
  "Scriptwriting and Screenwriting",
  "Memoir Writing",
  "Writing Children’s Books",
  "Literary Analysis and Critique",
  "Reading Historical Fiction",
  "Flash Fiction Writing",
  "Writing Creative Nonfiction",
  "Haiku and Short Poetry Writing",
  "Reading and Analyzing Philosophy",
  "Reading Contemporary Fiction",
  "Writing Mystery and Thriller",
  "Crafting Fantasy Worlds",
  "Travel Writing and Blogging",
  "Reading Biographies and Memoirs",
  "Self-Publishing Books",
  "Writing Young Adult Fiction",
  "Writing Comic Strips and Graphic Novels",
  "Experimental and Abstract Writing",
  "Writing for Magazines and Journals",
  "Reading Sci-Fi and Fantasy",
  "Short Story Writing",
  "Literary Event Attendance",
  "Writing Prompts and Challenges",
  "Philosophy and Ethical Studies",
  "Psychology and Human Behavior",
  "Personal Development Journaling",
  "Cognitive Science and Neuroscience",
  "Life Coaching and Mentorship",
  "Practicing Mindfulness",
  "Meditation and Self-Reflection",
  "Analyzing Dreams and Symbolism",
  "Studying Stoicism",
  "Positive Psychology",
  "Self-Awareness Practices",
  "Writing Affirmations and Manifestations",
  "Exploring Existentialism",
  "Hypnotherapy Basics",
  "Analyzing Personality Types (MBTI, Enneagram)",
  "Studying Eastern Philosophies (Zen, Taoism)",
  "Practicing Law of Attraction",
  "Exploring Spirituality",
  "Self-Discovery Activities",
  "Deep Listening and Empathy",
  "Exploring Ancient Wisdom Texts",
  "Journaling for Mental Clarity",
  "Practicing Self-Love and Acceptance",
  "Studying Behavioral Economics",
  "Resilience Building and Coping Skills",
  "Practicing Kindness and Compassion",
  "Moral Philosophy",
  "Studying Religious and Mystical Texts",
  "Counseling and Reflective Listening",
  "Practicing Public Speaking",
  "Sign Language Basics",
  "Debating and Argumentation",
  "Storytelling Techniques",
  "Conversation Skills Development",
  "Speech Writing and Presentation",
  "Practicing Charisma and Influence",
  "Writing and Performing Spoken Word Poetry",
  "Accent Training",
  "Social Etiquette and Manners",
  "Nonverbal Communication Mastery",
  "Personal Branding and Networking",
  "Teaching Language to Others",
  "Writing Persuasive Essays",
  "Verbal Reasoning and Logic",
  "Language Exchange Programs",
  "Practicing Negotiation Skills",
  "Foreign Language Translation",
  "Podcasting and Broadcasting",
  "Vocal Training and Projection",
  "Conducting Interviews",
  "Cultural Communication Skills",
  "Cross-Cultural Communication",
  "Reading and Interpreting Body Language",
  "Video Conferencing Skills",
  "Media and Journalism",
  "Writing Editorials and Opinion Pieces",
  "Enhancing Conversational Intelligence",
  "Comedy and Improvisation Skills",
  "Meditation Practices",
  "Yoga for Spiritual Growth",
  "Astrology and Horoscopes",
  "Numerology",
  "Chakra Healing and Balancing",
  "Tarot Card Reading",
  "Crystal Healing",
  "Energy Healing and Reiki",
  "Mindfulness and Mindful Living",
  "Shamanic Journeying",
  "Aura Reading",
  "Feng Shui and Space Cleansing",
  "Studying Esoteric and Occult Practices",
  "Sound Healing with Singing Bowls",
  "Manifestation Techniques",
  "Guided Visualization",
  "Studying World Religions",
  "Sacred Geometry",
  "Runes and Divination",
  "Akashic Records Exploration",
  "Breathwork and Pranayama",
  "Practicing Compassion Meditation",
  "Past Life Regression",
  "Mediumship Development",
  "Conscious Dreaming and Lucid Dreaming",
  "Learning Herbalism and Plant Medicine",
  "Exploring Ancient Spiritual Texts",
  "Learning Mantras and Chanting",
  "Practicing Gratitude Journals",
  "Sacred Rituals and Ceremonies",
  "Watching Classic Films",
  "Movie Reviews and Critiques",
  "Documentary Watching",
  "Animation and CGI",
  "Collecting Film Memorabilia",
  "Cinematography Appreciation",
  "Attending Film Festivals",
  "Watching Indie and Art Films",
  "Film History and Theory",
  "Screenwriting for Movies and TV",
  "Streaming TV Shows and Series",
  "Creating YouTube Content",
  "Voice Acting and Dubbing",
  "Video Editing",
  "Directing Short Films",
  "Creating Movie Fan Edits",
  "Podcast Listening",
  "Vlogging",
  "Video Production Techniques",
  "Watching Foreign Films",
  "Analyzing Film Scores",
  "Watching Theater Performances",
  "Behind-the-Scenes Filmmaking",
  "Watching Animated Shows",
  "Binge-Watching Series",
  "Acting and Auditioning",
  "Learning Film Special Effects",
  "Sound Design and Foley Art",
  "Watching Nature Documentaries",
  "Media Studies and Journalism",
  "Skydiving and Parachuting",
  "Rock Climbing (Bouldering, Free Climbing)",
  "Scuba Diving and Snorkeling",
  "Paragliding",
  "Whitewater Rafting",
  "Mountaineering",
  "Ice Climbing",
  "Free Diving",
  "BMX and Freestyle Biking",
  "BASE Jumping",
  "Surfing Big Waves",
  "Hang Gliding",
  "Kite Surfing",
  "Caving and Spelunking",
  "Downhill Mountain Biking",
  "Sandboarding",
  "Windsurfing",
  "Bungee Jumping",
  "Skateboarding Tricks",
  "Extreme Hiking and Trekking",
  "Rally Racing",
  "Ultra-Running (Endurance Races)",
  "Polar Expeditions",
  "Cliff Diving",
  "Gliding and Soaring",
  "Longboarding",
  "Barefoot Running",
  "Cave Diving",
  "Desert Racing",
  "Zero Waste Living",
  "Organic Gardening",
  "Composting Techniques",
  "Upcycling and Recycling Projects",
  "Permaculture Design",
  "Sustainable Architecture",
  "Renewable Energy Awareness",
  "Ecotourism",
  "Plastic-Free Lifestyle",
  "Plant-Based Eating",
  "Urban Gardening and Vertical Farms",
  "Supporting Local Farmers",
  "Minimalist Living",
  "Wildlife Conservation Volunteering",
  "Bee and Pollinator Gardening",
  "Community Clean-Up Events",
  "Environmental Activism",
  "Watershed Restoration",
  "Seed Saving and Exchange",
  "DIY Natural Household Products",
  "Eco-Friendly Fashion Choices",
  "Natural Cleaning Solutions",
  "Sustainable Fashion Design",
  "Water Conservation Techniques",
  "Studying Environmental Science",
  "Tree Planting Initiatives",
  "Rainwater Harvesting",
  "Organic Beekeeping",
  "Educating on Climate Change",
  "Advocating for Renewable Energy",
  "DIY Home Decor",
  "Furniture Refinishing",
  "Paper Crafting (Origami, Scrapbooking)",
  "Crochet and Knitting",
  "Embroidery and Needlework",
  "Resin Art Creations",
  "Polymer Clay Crafts",
  "Woodworking Projects",
  "Beading and Jewelry Making",
  "Pottery and Ceramic Art",
  "Macrame Wall Hangings",
  "Glass Painting",
  "Wood Burning (Pyrography)",
  "Fabric Dyeing and Tie-Dye",
  "Miniature Building (Dollhouses, Models)",
  "Upcycling Furniture",
  "Lace Making",
  "Shadow Box Art",
  "Quilting and Patchwork",
  "DIY Terrariums",
  "Mosaic Art Creations",
  "Flower Pressing",
  "Scrap Wood Crafts",
  "Dreamcatcher Making",
  "Mixed Media Art",
  "Cat Care and Training",
  "Aquarium and Fishkeeping",
  "Falconry",
  "Reptile Keeping",
  "Pet Grooming",
  "Small Mammal Care (Rabbits, Hamsters)",
  "Farm Animal Care",
  "Wildlife Conservation Projects",
  "Animal Assisted Therapy",
  "Aquarium Aquascaping",
  "Fostering Shelter Animals",
  "Rabbit Showmanship",
  "Working with Therapy Dogs",
  "Studying Animal Communication",
  "Raising Guide Dogs",
  "Chicken Keeping and Coop Building",
  "Learning Veterinary Basics (Non-Professional)",
  "Chess Strategy and Tactics",
  "Poker Strategy and Bluffing",
  "Go (Weiqi) Game Techniques",
  "Sudoku Puzzles",
  "Crossword Puzzle Solving",
  "Bridge Card Game",
  "Scrabble and Word Games",
  "Rubik’s Cube and Speedcubing",
  "Strategy Board Games (Risk, Catan)",
  "Backgammon",
  "Pinochle Card Game",
  "Mind Mapping and Visualization",
  "Logic Puzzles and Riddles",
  "Codebreaking and Cryptography",
  "Fantasy Sports Drafting",
  "Whist Card Game",
  "Mancala and Traditional Games",
  "Darts and Accuracy Games",
  "Real-Time Strategy Games",
  "Strategic War Games (Miniature)",
  "Competitive Card Games (Magic: The Gathering)",
  "Collecting and Solving Puzzle Boxes",
  "Kendoku Puzzles",
  "Contract Bridge",
  "Solitaire Variants",
  "Theoretical Physics",
  "Mathematics and Number Theory",
  "Archaeology",
  "Linguistics",
  "Astronomy and Space Science",
  "Genealogy and Family History",
  "Literature Analysis",
  "History and Ancient Civilizations",
  "Anthropology",
  "Political Science",
  "Art History",
  "Economics and Trade Theory",
  "Studying Law and Legal Systems",
  "Cryptography and Coding Theory",
  "Studying Neuroscience",
  "Environmental Science",
  "Exploring World Religions",
  "Social Psychology",
  "Analyzing Historic Texts",
  "Quantum Mechanics",
  "Ethics and Moral Philosophy",
  "Biomedical Engineering Concepts",
  "Intellectual Debates",
  "Study of Mythology and Folklore",
  "Volunteering at Animal Shelters",
  "Environmental Cleanup Efforts",
  "Disaster Relief Volunteering",
  "Donating and Organizing Blood Drives",
  "Community Garden Projects",
  "Organizing Fundraising Events",
  "Mentorship Programs for Youth",
  "Teaching Literacy",
  "Supporting Local Food Banks",
  "Elderly Care Volunteering",
  "Hospital Volunteering",
  "Refugee Support Services",
  "Building Homes for Habitat for Humanity",
  "Providing Free Tutoring",
  "Anti-Bullying Campaigns",
  "Organizing Donation Drives",
  "Advocating for Human Rights",
  "Mental Health Awareness",
  "Art Therapy Volunteering",
  "Supporting After-School Programs",
  "Organizing Book Drives",
  "Social Work with Families",
  "Teaching Financial Literacy",
  "Volunteering in Rural Development",
  "Mentoring Small Business Owners",
  "Providing Tech Assistance to Nonprofits",
  "Public Health Volunteering",
  "Women’s Rights Advocacy",
  "LGBTQ+ Support and Advocacy",
  "Youth Leadership Development",
  "Ballet Dancing",
  "Hip-Hop Dancing",
  "Ballroom Dancing (Salsa, Tango)",
  "Contemporary Dance",
  "Jazz Dance",
  "Tap Dancing",
  "Breakdancing",
  "Belly Dancing",
  "Folk Dancing (Irish, Greek, etc.)",
  "Swing Dancing",
  "Latin Dance (Bachata, Merengue)",
  "Pole Dancing",
  "Freestyle Dance",
  "Cultural Dance (Flamenco, Bollywood)",
  "Choreography and Dance Creation",
  "Competitive Dancing",
  "Dance Battles and Competitions",
  "Lyrical Dance",
  "Dance on Social Media (TikTok, Reels)",
  "Choir and Group Singing",
  "Jazz Singing",
  "Classical Singing",
  "Pop Singing",
  "Rap and Hip-Hop Vocals",
  "Musical Theater Singing",
  "Folk and Cultural Singing",
  "Rock and Alternative Singing",
  "Karaoke",
  "Vocal Training and Technique",
  "Acapella Singing",
  "Songwriting and Lyric Writing",
  "Harmonizing and Backing Vocals",
  "Performing Cover Songs",
  "Sound Cloud and Music Sharing",
  "Singing Competitions",
  "Recording Vocals at Home",
  "Social Media Music Covers",
  "Voice Exercises and Warm-Ups",
  "Improv Comedy",
  "Film and Television Acting",
  "Method Acting",
  "Monologue Practice",
  "Commercial Acting",
  "Acting for Musicals",
  "Physical Comedy",
  "Performing in Skits and Sketches",
  "Acting in Web Series",
  "Character Development for Acting",
  "Audition Preparation",
  "Studying Classic Plays",
  "Acting in Short Films",
  "Comedy Writing",
  "Drama Clubs and Local Theater",
  "Hosting and MC Skills",
  "Acting Techniques (Stanislavski, Meisner, etc.)",
  "Sketch Comedy Writing",
  "Physical Comedy and Slapstick",
  "Satire and Parody Creation",
  "Comedy Podcasting",
  "Comedy Vlogging",
  "Internet Meme Creation",
  "Dark Comedy",
  "Political Satire",
  "Comedy Scriptwriting",
  "Roasting and Comedy Battles",
  "Impressions and Celebrity Mimicry",
  "Comedy Acting in Film",
  "Writing Comedy Monologues",
  "Observational Humor",
  "Social Media Comedy (TikTok, Instagram Reels)",
  "Creating Viral Comedy Skits",
  "Comedy Sound Bites and Voiceovers",
  "Animation Comedy (Voices, Storylines)",
  "Vlogging and Video Blogging",
  "Short Video Creation (TikTok, Instagram Reels)",
  "Content Creation for YouTube",
  "Influencer Marketing and Branding",
  "Storytelling for Social Media",
  "Editing Short Videos",
  "Creating DIY Tutorials for Social Media",
  "Live Streaming (YouTube, Instagram, Twitch)",
  "Social Media Challenges",
  "Scripted Content for TikTok",
  "Viral Content Strategy",
  "Social Media Trends Analysis",
  "Creative Transitions in Short Videos",
  "Video Filters and Effects",
  "Engaging with Social Media Fans",
  "Interactive Social Media Content",
  "Fitness and Health Influencing",
  "Lifestyle Blogging on Social Platforms",
  "Music and Lip Syncing Videos",
  "Behind-the-Scenes Content",
  "Cinematography for Short Films",
  "Photography for Social Media",
  "Video Montage Creation",
  "Motion Graphics for Short Videos",
  "Graphic Design for Social Media Posts",
  "Animation for Short Clips",
  "Visual Storytelling Techniques",
  "Building Digital Portfolios",
  "Green Screen Effects",
  "Character Animation (2D and 3D)",
  "Creating Infographics",
  "Interactive Digital Art",
  "Digital Collage for Social Media",
  "Visual Content Strategy",
  "Creating Visual Effects (VFX)",
  "Artistic Editing Techniques",
  "Typography Design",
  "Stop-Motion Animation",
  "Sound Design and Foley for Video",
  "Mixed Media Content Creation"
]
export default Interests;