const occupations = [
  "Network Administration",
  "Helpdesk",
  "Web Development",
  "Mobile App Development",
  "Database Management",
  "Software Development",
  "IT Security",
  "Web Hosting Support",
  "Cloud Services",
  "Hardware Support",
  "Data Entry",
  "Virtual Assistant",
  "Transcription Services",
  "Document Management",
  "Office Administration",
  "Customer Service",
  "Project Management",
  "Calendar Management",
  "Market Research",
  "Accounting",
  "Tax Preparation",
  "Investment Advisory",
  "Bookkeeping",
  "Payroll",
  "Financial Planning",
  "Auditing",
  "Credit Repair",
  "Telemedicine",
  "Nursing",
  "Home Healthcare",
  "Medical Billing",
  "General Practitioner",
  "Physiotherapy",
  "Nutritionist",
  "Mental Health Counseling",
  "Special Education Support",
  "Homework Help",
  "Online Tutoring",
  "Career Coaching",
  "Study Assistance",
  "Test Preparation",
  "Digital Marketing",
  "Email Marketing",
  "CRM Management",
  "Content Writing",
  "Affiliate Marketing",
  "Social Media Management",
  "Copywriting",
  "Branding",
  "Lead Generation",
  "Legal Consultation",
  "Contract Drafting",
  "IP Law",
  "Employment Law",
  "Family Law",
  "Real Estate Law",
  "Document Review",
  "Employee Benefits",
  "Recruitment",
  "Resume Writing",
  "HR Management",
  "Career Counseling",
  "Conflict Resolution",
  "Logo Design",
  "Motion Graphics",
  "Video Editing",
  "Photography",
  "Illustration",
  "3D Modeling",
  "Graphic Design",
  "UI/UX Design",
  "Animation",
  "HVAC Services",
  "Electrician",
  "Cleaning",
  "Carpentry",
  "Plumbing",
  "Landscaping",
  "Pest Control",
  "Handyman Services",
  "Pet Care",
  "Fitness Coaching",
  "Personal Chef",
  "Travel Planner",
  "Translation",
  "Technical Writing",
  "Creative Writing",
  "Ghostwriting",
  "Copywriting",
  "Blog Writing",
  "Proofreading",
  "Acting Coaching",
  "Voice Acting",
  "Art Instruction",
  "Music Lessons",
  "Dance Instruction",
  "Theater Production Support",
  "Moving Services",
  "Fleet Management",
  "Courier",
  "Ride-Hailing",
  "Delivery Driver",
  "Freight Management",
  "Career Counseling",
  "Relationship Counseling",
  "Addiction Counseling",
  "Grief Counseling",
  "Mental Health Support",
  "Property Management",
  "Real Estate Agent",
  "Mortgage Brokering",
  "Real Estate Consulting",
  "Appraisal",
  "E-Commerce Store Setup",
  "Order Fulfillment",
  "Product Listing",
  "Inventory Management",
  "Customer Support",
  "Yoga Instructor",
  "Dietitian",
  "Massage Therapy",
  "Acupuncturist",
  "Herbalist",
  "Chiropractor",
  "Wellness Coach",
  "Band Manager",
  "Music Producer",
  "Sound Engineer",
  "Musician",
  "Music Teacher",
  "Music Therapist",
  "DJ",
  "Composer",
  "Lyricist",
  "Barber",
  "Nail Technician",
  "Skincare Specialist",
  "Tattoo Artist",
  "Hair Stylist",
  "Eyelash Specialist",
  "Waxing Specialist",
  "Makeup Artist",
  "Spa Services",
  "Sports Massage",
  "Sports Nutritionist",
  "Gym Management",
  "Personal Trainer",
  "Sports Agent",
  "Athletic Coach",
  "Fitness Instructor",
  "Food Stylist",
  "Catering",
  "Pastry Chef",
  "Restaurant Consultant",
  "Food Truck Services",
  "Chef",
  "Recipe Developer",
  "Mixologist",
  "Livestock Management",
  "Crop Consultant",
  "Horticulturist",
  "Irrigation Specialist",
  "Organic Farming",
  "Agricultural Engineer",
  "Building Inspector",
  "Civil Engineer",
  "Contractor",
  "Interior Designer",
  "Architect",
  "Structural Engineer",
  "Project Manager",
  "Auto Electrician",
  "Car Detailing",
  "Auto Body Repair",
  "Towing",
  "Tire Services",
  "Auto Mechanic",
  "Car Rental",
  "Costume Designer",
  "Tailor",
  "Wardrobe Consultant",
  "Fashion Designer",
  "Personal Shopper",
  "Fashion Buyer",
  "Concierge",
  "Travel Agent",
  "Hotel Consultant",
  "Travel Blogger",
  "Tour Guide",
  "Event Planner",
  "Cruise Ship Staff",
  "Nanny",
  "Early Childhood Educator",
  "Special Needs Educator",
  "Speech Therapist",
  "Babysitter",
  "Tutor",
  "Environmental Consultant",
  "Renewable Energy Consultant",
  "Solar Panel Installer",
  "Sustainability Expert",
  "Energy Auditor",
  "Pet Boarding",
  "Pet Sitter",
  "Veterinarian",
  "Dog Walker",
  "Pet Groomer",
  "Animal Trainer",
  "Pet Nutritionist",
  "Craftsperson",
  "Art Curator",
  "Calligrapher",
  "Muralist",
  "Art Restoration",
  "Digital Artist",
  "Fine Artist",
  "Tattoo Designer",
  "Content Creator",
  "Voiceover Artist",
  "Camera Operator",
  "Radio Host",
  "TV Presenter",
  "Podcast Host",
  "Ghostwriter",
  "Journalist",
  "Resume Writer",
  "Editor",
  "Scriptwriter",
  "Grant Writer",
  "PR Specialist",
  "AI Consultant",
  "AR Specialist",
  "Data Scientist",
  "IoT Consultant",
  "Blockchain Developer",
  "Drone Operator",
  "VR Developer",
  "Robotics Engineer",
  "IT Consultant",
  "Strategy Consultant",
  "Management Consultant",
  "Product Management",
  "Business Consultant"
]

export default occupations;