/**
 * Module: Report Error
 * Info:  Log non operation error for bug fixing for api response
 **/
const logger = require("../utils/logger");
const ApiError = require("./apiError");

/**
 * Log non operation error for bug fixing for api response
 * @param {Error Object} error
 */
const reportError = async (error) => {
  // Report error if error is non-operational generated by server , services and resource that not handled manually for debug later
  if (error instanceof ApiError) {
    if (!error.reported) {
      logger.error(error);
      error.reported = true;
    }
  } else {
    logger.warn("Non Api Error");
    logger.error(error);
  }
  return error;
};

module.exports = reportError;
